### ISSUE TITLE
proactive node auto-scaling pods cannot be scheduled when global priority is defined.

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/proactive-node-scaling-operator#3]
I've been testing the redhat-cop proactive-node-scaling-operator but ran into an issue.
When setting a globalDefault priority so "normal" workloads are always higher than the fake workloads it is impossible to schedule the proactive-node-scaling pods.

For example:
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
name: low-priority
value: 0
globalDefault: false
description: "This priority class is is the low-priority class for Proactive Node Scaling."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
name: normal-workload
value: 1000
globalDefault: true
description: "This priority classis the cluster default and should be used for normal workloads."
```
When using the proactive-node-scheduler the Pods can not be scheduled because "the integer value of priority (0) must not be provided in pod spec; priority admission controller computed 1000 from the given PriorityClass name".
A solution would be to use the priorityClassName instead of the Priority integer field in your operator.

Is this something you can verify and maybe fix? :)
